### ISSUE TITLE
새로 회원가입시 편리성 부분

### ISSUE THREAD

**Issue by imgzon3** [WeGrus/WeGrus-FE-React#66]
## Feature Description

버그는 아니지만, 회원가입을 할 때 불편함을 느낄 수 있을 것 같아 issue 올립니다!

![1번](https://user-images.githubusercontent.com/59475880/154795936-4537ef9c-29c8-4c8e-af2a-9384dc6764d1.png)
1. 우선 처음에 회원가입 시 학번을 적고, 제출 버튼을 눌렀습니다.

![2번](https://user-images.githubusercontent.com/59475880/154795975-f3f69b48-7dee-4127-8673-7e7707d20f2c.png)
2. 그 후 새 창(2번)에서 제 gmail로 넘어가졌고, 메일 인증 버튼을 눌렀습니다.

![3번](https://user-images.githubusercontent.com/59475880/154795998-ff73bdff-c9ee-4d1b-b40d-cbb27df15b54.png)
3. 그러자 또다른 창(3번)이 떳는데, 학번을 입력하라는 창이 또다시 떴습니다.

해당 과정에서 제가 잘못 기입했나 싶어 2번~3번정도 반복해봤는데, 알고보니 다시 1번 창으로 가니

![다시1번](https://user-images.githubusercontent.com/59475880/154796067-27e4a1e6-231f-4eb0-9e64-8a9012170c3c.png)
처음에 제출 버튼을 눌렀던 페이지에서 다음 단계 버튼이 떴습니다.
(해당 페이지를 스샷하지 못하여 그림판으로 대체합니다...)

실제로 회원가입할때 저처럼 여러번 반복할 수 있을거 같아 issue 남깁니다!

![image](https://user-images.githubusercontent.com/59475880/154796167-a62688b2-50d1-45a2-8fb2-9294a7fe45d2.png)
(여러번 반복한 흔적)

## Todo list

- [ ] 회원가입 개선

**Comment by biinggala** [comment]
회원가입 완료 시 이전 페이지로 돌아가라는 메시지 출력하도록 로직 변경 완료하였습니다.
