### ISSUE TITLE
[About] 간격 조정

### ISSUE THREAD

**Issue by seonpilKim** [WeGrus/WeGrus-FE-React#68]
## Feature Description

- 체크한 부분 간격을 넓혀주세요.
    - ![image](https://user-images.githubusercontent.com/68049320/154810277-84792e4b-5dec-400f-9d87-a5ba7128779d.png)

## Todo list

- [ ] 간격 조정

**Comment by biinggala** [comment]
<img width="987" alt="스크린샷 2022-02-22 02 07 23" src="https://user-images.githubusercontent.com/49203064/154999961-42507202-a36a-44cf-9e4a-28e379fffde4.png">
저는 간격이 꽤 넓게 나옵니다. 사용 환경에 따라 다른 것 같아요

**Comment by seonpilKim** [comment]
폰트 설정하신 거 있으신지 확인 부탁드립니다. 
폰트가 달라서 이렇게 보이는 거라면 폰트를 통일하면 좋을 것 같습니다.

**Comment by biinggala** [comment]
수정 완료했습니다.

**Comment by biinggala** [comment]
@seonpilKim 수정했습니다. 변경사항이 저장 되었는지 확인해주세요!
