### ISSUE TITLE
[게시물 목록] 댓글이 없는 게시물은 댓글 수 표시 제거

### ISSUE THREAD

**Issue by seonpilKim** [WeGrus/WeGrus-FE-React#69]
## Feature Description

- 댓글이 없는 게시물은 제목 오른쪽의 댓글 수 표시를 제거해주세요.
    - ![image](https://user-images.githubusercontent.com/68049320/154810354-bb3dd4aa-6bd1-4c42-a9b2-fea391f1077a.png)

## Todo list

- [x] 댓글이 없는 게시물은 댓글 수 표시 제거

**Comment by dmdgpdi** [comment]
수정했습니다. 추후 빌드하고 때 확인해보겠습니다.
