### ISSUE TITLE
[게시물] 추천 클릭 시, 배경색 변환 추가

### ISSUE THREAD

**Issue by seonpilKim** [WeGrus/WeGrus-FE-React#70]
## Feature Description

- 추천 클릭 시, 배경색 변환 추가해주세요. 스크랩만 변환되네요.
    - ![image](https://user-images.githubusercontent.com/68049320/154810399-98061573-2b44-43c5-8e1a-43a86a0ce4b7.png)

## Todo list

- [ ] 추천 클릭 시, 배경색 변환 추가

**Comment by dmdgpdi** [comment]
추천 관련 함수 로직 변경 했습니다. 이후 build하고 확인하겠습니다.

**Comment by seonpilKim** [comment]
@dmdgpdi 
#72 도 참고해주세요.

**Comment by dmdgpdi** [comment]
#72 도 확인했고 수정 하겠습니다!

**Comment by dmdgpdi** [comment]
build 후 문제없음을 확인했습니다.
