### ISSUE TITLE
직접 페이지 링크 입력 시, 제대로 페이지 이동이 안되는 현상

### ISSUE THREAD

**Issue by seonpilKim** [WeGrus/WeGrus-FE-React#73]
## Describe the bug

> 어떤 버그인지 설명해주세요.

- 예를 들어, 로그인한 상태에서 igrus.net/board를 주소창에 입력하면 about 페이지로 이동됨

## To Reproduce

> 버그를 재현하는 과정을 설명해주세요.

설명 참고

## Expected behavior

> 기대하는 결과를 설명해주세요.

- 주소창에 입력한 페이지로 이동(권한 부족할 시 적절한 페이지로 리다이렉트)

**Comment by dmdgpdi** [comment]
현재 중첩 라우트로 설계되었기에 이런 문제가 발생한다고 생각합니다. 따라서 중첩 라우팅을 풀고 현재 하고있는 뒤로가기 로직 수정후에 수정할 예정입니다.

**Comment by dmdgpdi** [comment]
현재 수정 중입니다.

**Comment by dmdgpdi** [comment]
@biinggala 지금까지 로직을 살펴보니 app.js userReducer.roles의 null 유무로 게시판의 접근이 주어지는데 새로고침이나 페이지 링크 입력시 userReducer가 초기화되며 userReducer.roles가 null이 되어 자동으로 about 페이지로 이동됩니다. 로그인 유무를 세션에 저장할 수 있으면 좋을 것 같습니다.

**Comment by dmdgpdi** [comment]
Reducer로 판단하는 것을 없애고, 세션 스토리지에 roles를 저장해 접근권한 유무를 파악하는 것으로 변경하기로 했습니다.

**Comment by seonpilKim** [comment]
@dmdgpdi 
새로고침이나 페이지 이동 시, accesstoken이 초기화되므로 재발급 요청 api -> 본인 정보 조회 api 호출 순으로 권한을 가져오시면 됩니다.
스토리지에 저장하는 건 보안적으로 좋지 않은 것 같습니다.

**Comment by biinggala** [comment]
@seonpilKim 말씀하신 방법대로 하면 리이슈 api 호출 전 짧은 시간동안 유저의 role을 확인할 수 없어서 about으로 redirect 됩니다...

**Comment by biinggala** [comment]
@seonpilKim sesssion storage 값을 난독화 하는 것은 어떨까요?

**Comment by biinggala** [comment]
해결하였습니다.
