### ISSUE TITLE
[게시물] 게시물 작성 중 페이지 이동 시 재확인 alert 추가

### ISSUE THREAD

**Issue by seonpilKim** [WeGrus/WeGrus-FE-React#74]
## Feature Description

- 게시물 작성 중 페이지 이동 시 alert 추가
    - 목록으로 이동 or 새로고침 or 페이지 이동 등 현 페이지를 벗어나는 경우 재확인 alert 추가

## Todo list

- [x] 게시물 작성 중 페이지 이동 시 alert 추가

**Comment by dmdgpdi** [comment]
[beforeunload](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event)
[react-beforeunload](https://www.npmjs.com/package/react-beforeunload)
[beforeunload 직접 구현](https://j3sung.tistory.com/683)
[Prompt 창 띄우는 법](https://kyung-a.tistory.com/36)

두번째 link인 react-beforeunload로 새로고침을 확인받고 Prompt 창 띄우는 법 링크를 참고해서 뒤로가기 및 목록으로 돌아가기를 막을 수 있게 수정했습니다. 게시물 작성 버튼을 누르면 alert가 동작하지 않는 것을 확인했습니다.
