### ISSUE TITLE
[댓글] 답글 배경색 변경

### ISSUE THREAD

**Issue by seonpilKim** [WeGrus/WeGrus-FE-React#75]
## Feature Description

- 답글 배경색을 좀 더 연한 색으로 변경해주세요.
    - ![image](https://user-images.githubusercontent.com/68049320/154810964-ed7b5d95-6509-4f74-9c6b-4fb8131d4b38.png)
    - 참고(에브리타임)
        - ![image](https://user-images.githubusercontent.com/68049320/154810985-26f2f550-85e3-42d5-b243-91b0e8855f6a.png)

## Todo list

- [x] 답글 배경색 변경

**Comment by dmdgpdi** [comment]
수정했습니다.
