### ISSUE TITLE
[댓글] content 영역 위치 조정

### ISSUE THREAD

**Issue by seonpilKim** [WeGrus/WeGrus-FE-React#76]
## Feature Description

- 댓글 content 영역 위치를 전체적으로 왼쪽으로 이동하면 좋을 것 같습니다.
    - ![image](https://user-images.githubusercontent.com/68049320/154811065-3e930e9a-dfdd-46f7-8e96-ed007f9fb02c.png)

## Todo list

- [ ] 댓글 content 영역 위치 조정

**Comment by dmdgpdi** [comment]
수정했습니다.
