### ISSUE TITLE
[댓글] textarea 크기 조정 제어

### ISSUE THREAD

**Issue by seonpilKim** [WeGrus/WeGrus-FE-React#77]
## Feature Description

- 댓글 입력 하는 textarea 크기 조정을 못하도록 수정해주세요. 아래와 같이 늘리면 화면이 이상해집니다.
    - ![image](https://user-images.githubusercontent.com/68049320/154811121-4322af4c-1b0d-4109-80d3-fc7099270a80.png)

## Todo list

- [x] 댓글 textarea 크기 조정 제어

**Comment by dmdgpdi** [comment]
크기 조정을 못하도록  resize: none; 설정을 부여했습니다.
