### ISSUE TITLE
[내 정보] 본인 정보 조회 API 적용

### ISSUE THREAD

**Issue by seonpilKim** [WeGrus/WeGrus-FE-React#81]
## Feature Description

- 본인 정보 조회 API (`/info`) 적용해주세요. `ROLE_GUEST` 권한으로 설정하였습니다.
    - ![image](https://user-images.githubusercontent.com/68049320/154834263-691f6626-1036-4bfc-a3c5-aac4fd86599e.png)

## Todo list

- [ ] 본인 정보 조회 API 적용

**Comment by biinggala** [comment]
1. /info api로 수정 완료하였습니다.
2. 게스트 권한일 경우 회원 정보는 조회 가능, 정보 수정은 불가능, 회원 탈퇴는 가능하도록 수정했습니다.
