### ISSUE TITLE
[게시물] 회원 등급에 따를 게시판 이용 설정 변경

### ISSUE THREAD

**Issue by dmdgpdi** [WeGrus/WeGrus-FE-React#83]
## Feature Description

- 회원이지만 등록 안된 이들은 게시물 목록 조회는 가능하게, 게시물 조회나 생성은 불가능
- description 2

## Todo list

- [ ] todo 1
- [ ] todo 2
- [ ] todo 3

**Comment by biinggala** [comment]
게스트 권한일 때 게시물 조회 시 경고 메시지를 뜨게 하고 about 페이지로 돌아가도록 수정했습니다.
