### ISSUE TITLE
[게시물] 게시물 첨부파일 다운 시, 사이트에서 나가시겠습니까? 라는 문구 출력

### ISSUE THREAD

**Issue by imgzon3** [WeGrus/WeGrus-FE-React#86]
## Feature Description

- 게시물 첨부파일 다운 시, 사이트에서 나가시겠습니까? 라는 문구 출력
  - ![image](https://user-images.githubusercontent.com/59475880/154863799-244cd682-aa3b-4622-85b5-2280a9607e4e.png)

## Todo list

- [ ] 문구 출력 안되도록 변경

**Comment by dmdgpdi** [comment]
게시글 작성 부분에서 넣으려던 속성이었으나 전체 적용됨을 확인할 수있었습니다. 수정하겠습니다.
