### ISSUE TITLE
[마이페이지] 내가 쓴 게시글/댓글, 저장한 게시글 게시물 클릭

### ISSUE THREAD

**Issue by imgzon3** [WeGrus/WeGrus-FE-React#87]
## Describe the bug

> 어떤 버그인지 설명해주세요.

- 아직 미구현인지는 잘 모르겠으나,
- 마이페이지에서 내가 쓴 게시글의 게시물을 클릭할 경우, There's nothing here!라는 페이지로 이동합니다.
- 마이페이지에서 내가 쓴 댓글의 게시물을 클릭할 경우, There's nothing here!라는 페이지로 이동합니다.
- 마이페이지에서 저장한 게시글의 게시물을 클릭할 경우, There's nothing here!라는 페이지로 이동합니다.

### Screenshots (Optional)
![ㅁㄴㅇㄹ](https://user-images.githubusercontent.com/59475880/154864110-4a1d7c8d-240c-4852-b577-6565c6b30d8d.png)
![image](https://user-images.githubusercontent.com/59475880/154864127-ae44453c-0960-4e07-9cb6-31d70bac4c4b.png)
![ㅂㅈㄷ](https://user-images.githubusercontent.com/59475880/154864208-96bf844d-8dcd-43cf-ab2d-af1d0e89e51b.png)
![image](https://user-images.githubusercontent.com/59475880/154864212-71f324a2-3285-4941-9713-b54c5b84ac6c.png)
![ㅋㅌㅊ](https://user-images.githubusercontent.com/59475880/154864250-7929bbc2-d13c-4c58-b11b-fa44e64a95c7.png)
![image](https://user-images.githubusercontent.com/59475880/154864253-d936af89-face-43a6-b68e-35bab58e1236.png)

## To Reproduce

> 버그를 재현하는 과정을 설명해주세요.

설명 참고

## Expected behavior

> 기대하는 결과를 설명해주세요.

- 해당 게시물로 이동한다.

**Comment by biinggala** [comment]
새 탭에서 해당 게시글로 이동하도록 구현하겠습니다!

**Comment by biinggala** [comment]
새 탭 말고 해당 탭에서 페이지 이동하도록 구현 완료했습니다!
